FROM nginx:alpine

RUN apk add --no-cache openssl apache2-utils

COPY nginx.conf /etc/nginx/nginx.conf
COPY html/ /usr/share/nginx/html/

RUN mkdir -p /etc/nginx/ssl /etc/nginx/auth && \
    openssl req -x509 -nodes -newkey rsa:2048 \
    -keyout /etc/nginx/ssl/server.key \
    -out /etc/nginx/ssl/server.crt \
    -days 365 \
    -subj "/C=ES/ST=Madrid/L=Madrid/O=UNIR/OU=DevOps/CN=cp2-webserver" && \
    htpasswd -bc /etc/nginx/auth/htpasswd "cp2user" "cp2pass"

EXPOSE 443
CMD ["nginx", "-g", "daemon off;"]