---
ACR_LOGIN_SERVER: "{{ lookup('env', 'CP2_ACR_LOGIN_SERVER') }}"
ACR_USERNAME: "{{ lookup('env', 'CP2_ACR_USERNAME') }}"
ACR_PASSWORD: "{{ lookup('env', 'CP2_ACR_PASSWORD') }}"

REDIS_IMAGE_NAME: "redis"
REDIS_IMAGE_TAG: "casopractico2"
REDIS_IMAGE_FULL: "{{ ACR_LOGIN_SERVER }}/{{ REDIS_IMAGE_NAME }}:{{ REDIS_IMAGE_TAG }}"

REDIS_UPSTREAM_IMAGE: "docker.io/library/redis:alpine"
