all:
  children:
    local:
      hosts:
        localhost:
          ansible_connection: local

    vm:
      hosts:
        cp2-vm:
          ansible_host: "{{ lookup('env','CP2_VM_IP') }}"
          ansible_user: alloci
          ansible_ssh_private_key_file: ../terraform/cp2_ssh_key.pem
