---
- name: CP2 - Build & Push images to ACR (local)
  hosts: local
  gather_facts: false
  roles:
    - acr

- name: CP2 - Deploy webserver on VM (Podman + systemd)
  hosts: vm
  become: true
  gather_facts: true
  roles:
    - vm

- name: CP2 - Deploy Voting App on AKS
  hosts: local
  gather_facts: false
  roles:
    - aks
